Areas/Events/Controllers/CollectionEventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Management;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using OH.BLL;
using OH.BLL.Models.Events;
using OH.BLL.Models.TimeStamps;
using OH.BLL.Services.Events;
using OH.BLL.Services.Staff;

namespace OH.Net.Areas.Events.Controllers
{
    public class CollectionEventController : Controller
    {
        private readonly ICollectionEventBllService _collectionEventBllService;
        private readonly ICollectionLocationBllService _collectionLocationBllService;
        private readonly ICollectionEventOfficeMappingBllService _collectionEventOfficeMappingBllService;
        public CollectionEventController(ICollectionEventBllService collectionEventBllService, ICollectionLocationBllService collectionLocationBllService, ICollectionEventOfficeMappingBllService collectionEventOfficeMappingBllService)
        {
            _collectionEventBllService = collectionEventBllService;
            _collectionLocationBllService = collectionLocationBllService;
            _collectionEventOfficeMappingBllService = collectionEventOfficeMappingBllService;
        }

        // GET: Events/CollectionEvent
        public ActionResult Index()
        {
            ViewBag.inline = (new StaffMenuService()).GetInlineData();
            return View();
        }



        [HttpGet]
        public PartialViewResult New()
        {
            ViewBag.Offices = _collectionEventBllService.GetOffices();
            ViewBag.isNew = true;

            var g = _collectionEventBllService.Initialize();
            return PartialView("_New", g);
        }
        //[HttpGet]
        //public JsonResult GetEmpty()
        //{
        //    ViewBag.Offices = _collectionEventBllService.GetOffices();
        //    return Json(data: new CollectionEventViewModel(), behavior: JsonRequestBehavior.AllowGet);
        //}

        [HttpPost]
        public PartialViewResult New(CollectionEventViewModel c)
        {

            //Tuck Stuff
            //if (!ModelState.IsValid)
            //{
            // throw new Exception("Unexpected model state errror when saving new collection event");   
            //}
            ////do save
            //var g=_collectionEventBllService.Initialize();
            ////c = _collectionEventBllService.GetById(g);
            //return PartialView("_CollectionEventContainer",g);


            //c.Participants = _collectionEventBllService.GetOffices(c.Participants);



            if (ModelState.IsValid)
            {
                var g = _collectionEventBllService.UpdateEvent(c);
                return PartialView("_CollectionEventContainer", g);
            }
            ViewBag.isNew = false;
            ViewBag.Offices = _collectionEventBllService.GetOffices();
            return PartialView("_New", c);

        }

        public JsonResult GetOfficesList()
        {
            var offices = _collectionEventBllService.GetOffices();
            return Json(offices, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public PartialViewResult Edit(string id)
        {
            ViewBag.Offices = _collectionEventBllService.GetOffices();
            ViewBag.isNew = false;
            var c =  _collectionEventBllService.GetById(new Guid(id));
            
            return PartialView("_New", c);
        }

        [HttpPost]
        public void Edit(CollectionEventViewModel c)
        {
            var g = _collectionEventBllService.UpdateEvent(c);
            //return RedirectToAction("GetEventTabs", new {id = g.ToString()});
            //return PartialView("_CollectionEventContainer", new Guid(c.MeetingID));
        }
        //public ActionResult Locations(Guid id)
        //{
            
        //    return PartialView("_Locations",id);
        //}

        public ActionResult Locations(string id)
        {
            return PartialView("_Locations", id);
        }

       // public PartialViewResult GetEventTabs(string id) { return PartialView("_CollectionEventContainer", new Guid(id)); }
        public PartialViewResult GetEventTabs(Guid id) { return PartialView("_CollectionEventContainer", id); }
        [HttpPost]
        public JsonResult Create_CollectionLocation([DataSourceRequest] DataSourceRequest request, CollectionLocationMappingViewModel collectionLocationMappingViewModel)
        {
            return Json(new[] {_collectionEventBllService.AddCollectionLocationMapping(collectionLocationMappingViewModel)}.ToDataSourceResult(request));
        }


        public JsonResult Read_CollectionLocation([DataSourceRequest] DataSourceRequest request, string id)
        {
            

            var c = _collectionEventBllService.GetById(new Guid(id));
            var m =  c.Locations ?? _collectionLocationBllService.Initialize(); //_collectionEventBllService.GetOffices(c.Participants.Select(p => p.CollectionOfficeId).ToArray());
            return Json(m.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Update_CollectionLocation([DataSourceRequest] DataSourceRequest request, CollectionLocationMappingViewModel collectionLocationMappingViewModel)
        {
            if (collectionLocationMappingViewModel != null && ModelState.IsValid)
                collectionLocationMappingViewModel = _collectionEventBllService.UpdateCollectionLocationMapping(collectionLocationMappingViewModel);
            else{
                foreach (var modelState in ViewData.ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        var m = error.ErrorMessage;
                        var e = error.Exception;
                    }
                }
            }
            return Json(new[] { collectionLocationMappingViewModel }.ToDataSourceResult(request, ModelState));
        }

        [HttpPost]
        public ActionResult Delete_CollectionLocation([DataSourceRequest] DataSourceRequest request, CollectionLocationMappingViewModel collectionLocationMappingViewModel)
        {
            if (collectionLocationMappingViewModel != null)
                //TUCKER   _collectionEventBllService.DeleteCollectionLocationMapping(collectionLocationMappingViewModel.Id.Value);
                _collectionEventBllService.DeleteCollectionLocationMapping(collectionLocationMappingViewModel.Id);
            return Json(new[] { collectionLocationMappingViewModel }.ToDataSourceResult(request, ModelState));
        }

        public PartialViewResult Volunteers(Guid id)
        {
            return PartialView("_Volunteers",id);
        }

        public PartialViewResult Volunteers(string id)
        {
            return PartialView("_Volunteers", id);
        }
        public JsonResult Read_CollectionVolunteer([DataSourceRequest] DataSourceRequest request, string id)
        {
            var c = _collectionEventBllService.GetById(new Guid(id));
            var m = c.Volunteers ?? new List<CollectionVolunteerMappingViewModel>();
            return Json(m.ToDataSourceResult(request));
        }

        [HttpPost]
        public JsonResult Create_CollectionVolunteer([DataSourceRequest] DataSourceRequest request, CollectionVolunteerMappingViewModel collectionVolunteerMappingViewModel)
        {
            //TUCKER   return Json(new[] {_collectionEventBllService.AddOrUpdateCollectionVolunteerMapping(collectionVolunteerMappingViewModel)}.ToDataSourceResult(request));
            return Json(new[] {_collectionEventBllService.AddOrUpdateCollectionVolunteerMapping(collectionVolunteerMappingViewModel)}.ToDataSourceResult(request));
        }

        [HttpPost]
        public ActionResult Update_CollectionVolunteer([DataSourceRequest] DataSourceRequest request, CollectionVolunteerMappingViewModel collectionVolunteerMappingViewModel)
        {
            if (collectionVolunteerMappingViewModel != null && ModelState.IsValid)
                //TUCKER   collectionVolunteerMappingViewModel = _collectionEventBllService.AddOrUpdateCollectionVolunteerMapping(collectionVolunteerMappingViewModel);
                collectionVolunteerMappingViewModel = _collectionEventBllService.AddOrUpdateCollectionVolunteerMapping(collectionVolunteerMappingViewModel);
            return Json(new[] { collectionVolunteerMappingViewModel }.ToDataSourceResult(request, ModelState));
        }
        [HttpPost]
        public ActionResult Delete_CollectionVolunteer([DataSourceRequest] DataSourceRequest request, CollectionVolunteerMappingViewModel collectionVolunteerMappingViewModel)
        {
            if (collectionVolunteerMappingViewModel != null)
                //TUCKER   _collectionEventBllService.DeleteCollectionLocationMapping(collectionVolunteerMappingViewModel.Id.Value);
                _collectionEventBllService.DeleteCollectionLocationMapping(collectionVolunteerMappingViewModel.Id);
            return Json(new[] { collectionVolunteerMappingViewModel }.ToDataSourceResult(request, ModelState));
        }



    }
}

Areas/Events/Views/CollectionEvent/Index.cshtml
@*@{
    Layout = "~/Areas/Events/Views/CollectionEvent/Index.cshtml";
}*@

@section LeftMenu
{
    @Html.Partial("~/Areas/Events/Views/Staff/_PartialNav.cshtml")
}

<div id="displayContent" style="height: 100%">

</div>

Areas/Events/Views/CollectionEvent/_CollectionEventContainer.cshtml
@using Kendo.Mvc.UI
@using OH.BLL.Models.Addresseses
@using OH.BLL.Models.Events;
@using OH.BLL.Models.TimeStamps
@model Guid


<script type="text/javascript">


    function onActivate() {
        
        var ts = $("#collectionEventTabStrip").data().kendoTabStrip;
        ts.tabGroup.on('click', 'li', function () {
            ts.reload($(this));
        });
    }


        function refreshCurrentTab() {
            var ts = $("#collectionEventTabStrip").data().kendoTabStrip;
            ts.reload($("ul.k-tabstrip-items>li.k-state-active"));
        }

    </script>
@(Html.Kendo()
            .TabStrip()
            .Name("fsgfsgbsf")
            .HtmlAttributes(new { style = "width:1060px", id = "collectionEventTabStrip" })
            .Events(a=>a.Activate("onActivate"))
            .Items(tabstrip =>
                {
                    tabstrip.Add().Text("Locations").Enabled(true).Selected(true).Content(@Html.Action("Locations","CollectionEvent",Model.ToString()).ToHtmlString());//("//.LoadContentFrom("Locations", "CollectionEvent", new { id = Model.ToString() });
                    tabstrip.Add().Text("Volunteers").Enabled(true).LoadContentFrom("Volunteers", "CollectionEvent", new { id = Model.ToString() });
            })
)

Areas/Events/Views/CollectionEvent/_Locations.cshtml
@using Kendo.Mvc.UI
@using OH.BLL.Models.Addresseses
@using OH.BLL.Models.Events;
@using OH.BLL.Models.TimeStamps
@model string
   @*  @model CollectionEventViewModel*@


                  <script type="text/javascript">
                      $(document).ready(function () {
                      });

                      function showLocationDetails(e) {
                          
                          e.preventDefault();
                          var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
                          var u = "@Url.Action("Edit","CollectionEvent",null)" + "/" + dataItem.MeetingID;
                          $("#displayContent").load(u);
                      }


                      function onRequestEnd(e) {
                          for (var i = 0; i < e.response.Data.length; i++) {
                              if (e.response.Data[i].CollectionLocation && e.response.Data[i].CollectionLocation.OpeningOnUtc) {
                                  e.response.Data[i].CollectionLocation.OpeningOnUtc = kendo.parseDate(e.response.Data[i].CollectionLocation.OpeningOnUtc);
                              }
                              if (e.response.Data[i].CollectionLocation && e.response.Data[i].CollectionLocation.TimeStamp && e.response.Data[i].CollectionLocation.TimeStamp.UtcCreatedDate) {
                                  e.response.Data[i].CollectionLocation.TimeStamp.UtcCreatedDate = kendo.parseDate(e.response.Data[i].CollectionLocation.TimeStamp.UtcCreatedDate);
                              }
                              if (e.response.Data[i].CollectionLocation && e.response.Data[i].CollectionLocation.TimeStamp && e.response.Data[i].CollectionLocation.TimeStamp.UtcLastModifiedDate) {
                                  e.response.Data[i].CollectionLocation.TimeStamp.UtcLastModifiedDate = kendo.parseDate(e.response.Data[i].CollectionLocation.TimeStamp.UtcLastModifiedDate);
                              }
                              if (e.response.Data[i].CollectionLocation && e.response.Data[i].CollectionLocation.Address && e.response.Data[i].CollectionLocation.Address.TimeStamp && e.response.Data[i].CollectionLocation.Address.TimeStamp.UtcCreatedDate) {
                                  e.response.Data[i].CollectionLocation.Address.TimeStamp.UtcCreatedDate = kendo.parseDate(e.response.Data[i].CollectionLocation.Address.TimeStamp.UtcCreatedDate);
                              }
                              if (e.response.Data[i].CollectionLocation && e.response.Data[i].CollectionLocation.Address && e.response.Data[i].CollectionLocation.Address.TimeStamp && e.response.Data[i].CollectionLocation.Address.TimeStamp.UtcLastModifiedDate) {
                                  e.response.Data[i].CollectionLocation.Address.TimeStamp.UtcLastModifiedDate = kendo.parseDate(e.response.Data[i].CollectionLocation.Address.TimeStamp.UtcLastModifiedDate);
                              }
                          }
                      }



        </script>

@(Html.Kendo().Grid<CollectionLocationViewModel>()
            .Name("Grid")
            .Columns(columns =>
            {
                columns.Bound(p => p.AddressCity).Title("City");
                columns.Bound(p => p.AddressState).Title("State").Width(85);
                columns.Bound(p => p.PointOfInterest).Title("POI");
                columns.Bound(p => p.StoreNumber).Title("Store #").Width(95);
                columns.Bound(p => p.VolunteerName).Title("Volunteer");
                columns.Bound(p => p.AvailOn).Title("Avail On");
                 })
                
                .DataSource(dataSource => dataSource
                .Ajax()
                .PageSize(20)
                
                .Read(read => read.Action("Read_CollectionLocation", "CollectionEvent", new { id = Model }))
                
                )                 
           

)




        @*@(Html.Kendo().Grid<CollectionLocationMappingViewModel>()
            .Name("Grid")
            .Columns(columns =>
            {

                columns.Bound(p => p.CollectionLocation.AddressCity).Title("City");
                columns.Bound(p => p.CollectionLocation.AddressState).Title("State").Width(85);
                columns.Bound(p => p.CollectionLocation.PointOfInterest).Title("POI");
                columns.Bound(p => p.CollectionLocation.StoreNumber).Title("Store #").Width(95);
                columns.Bound(p => p.CollectionLocation.VolunteerName).Title("Volunteer");
                columns.Bound(p => p.CollectionLocation.AvailOn).Title("Avail On");
                columns.Command(command =>
                {
                    command.Edit();
                    command.Destroy();
                });
            })
            .Pageable()
            .Sortable()
            .Scrollable()
            .Filterable()
            .Editable(editable => editable.Mode(GridEditMode.PopUp).Window(s =>
            {
                s.Height(600);
                s.Width(425);
                s.Title("Location Information");
            }
            ).TemplateName(@"Custom/CollectionLocationMapping")
            )
            .ToolBar(
              a => a.Template(@<text>
                                    <div class="toolbar">
                                        <input class='k-button k-button-icontext' type="button" onclick="refreshCurrentTab()" value="Refresh" />&nbsp;&nbsp;&nbsp;
                                        <input class='k-button k-button-icontext k-grid-add' type="button" value="Attach Location" />&nbsp;&nbsp;&nbsp;
                                    </div>
                                </text>)
                )
            .DataSource(dataSource => dataSource
                .Ajax()
                .PageSize(20)
                .Events(e=>e.RequestEnd("onRequestEnd"))
                        .Model(model =>
                        {
                            model.Id(p => p.Id);
                            model.Field(p => p.CollectionLocation).DefaultValue(new CollectionLocationViewModel());
                            model.Field(p => p.CollectionEventId).DefaultValue(new Guid(Model));
                            model.Field(p => p.CollectionLocationId).DefaultValue(Guid.Empty);
                         
                        })
                .Create(create => create.Action("Create_CollectionLocation", "CollectionEvent"))
                .Read(read => read.Action("Read_CollectionLocation", "CollectionEvent", new { id = Model }))
                .Update(update => update.Action("Update_CollectionLocation", "CollectionEvent"))
                        .Destroy(update => update.Action("Delete_CollectionLocation", "CollectionEvent"))
            )
        )*@

Areas/Events/Views/CollectionEvent/_New.cshtml
@using Kendo.Mvc.UI
@using OH.BLL.Models.Events
@using OH.BLL.Models.Addresseses
@using OH.BLL.Models.TimeStamps
@*@using OH.Net.Helpers*@
@model CollectionEventViewModel
@{
    //ViewContext.ClientValidationEnabled = false;
    //HtmlHelper.ClientValidationEnabled = false;

    string owner = (Model.Owner!=null)?Model.Owner.Id.ToString():string.Empty;
    //var offices = (IEnumerable<OfficeViewModel>) ViewBag.Offices;
    //var olist = offices.ToList().Select(a => new SelectListItem() { Text = a.InternalName, Value = a.Id.ToString() }).ToList();
    var range = new List<SelectListItem>();




    for (int i = 5; i < 201; i += 5)
    {
        var item = new SelectListItem {Text = i.ToString(), Value = i.ToString()};

        range.Add(item);
    }


    var maxStores = new List<SelectListItem>();
    for (int i = 1; i < 26; i++)
    {
        var item = new SelectListItem {Text = i.ToString(), Value = i.ToString()};

        maxStores.Add(item);
    }


    var saveAsNew = (bool) ViewBag.isNew;
   // var addressVerifyKey = "AddressVerifyHtmlKey".GetAppSetting();
}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<div id="formHolder" style="width: 30%;float: left;">

    @*@using (Ajax.BeginForm(saveAsNew ? "New" : "Edit", null, options, new { @id = "newCollectionEventForm" }))*@
    @using (Html.BeginForm("New", "CollectionEvent", FormMethod.Post, new { id = "collectionEventForm" }))
    {

        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()
        @Html.LabelFor(m => m.Title)<br />
        @Html.EditorFor(m => m.Title)<br />
        @Html.ValidationMessageFor(m => m.Title)<br />
        @Html.LabelFor(m => m.Owner)<br />
        //@Html.Kendo().DropDownListFor(m => m.OwnerId).Name("OwnerId").BindTo(olist).Value(owner).HtmlAttributes(new { style = "width:300px" })<br />
            
        
        @Html.LabelFor(m => m.Participants)<br />
        //@Html.Kendo().MultiSelect().Name("Participants").Placeholder("Participating Offices").BindTo(olist).Value(Model.Participants).HtmlAttributes(new { style = "width:300px" })
        //@Html.Kendo().MultiSelect().MultiSelectFor(model => model.Participants)
                //.Name("Participants2")
                //    .Placeholder("Participating Offices")
                    //.BindTo(new SelectList(offices, "Id","InternalName"))
                    //.DataTextField("InternalName")
                    //.DataValueField("Id")
                    //.Value(Model.Participants)
                    //.HtmlAttributes(new { style = "width:300px" })
                    
                    @(Html.Kendo().MultiSelectFor(m => m.ParticipantsFromView)
                      .Placeholder("Participating Offices")
                      .DataSource(source =>
                          {
                              source.Read(read =>
                              {
                                  read.Action("GetOfficesList", "CollectionEvent");
                              })
                              .ServerFiltering(true);
                          })
                         .DataValueField("Value")
                         .DataTextField("Text")
                      //  .BindTo(new SelectList(offices, "Id", "InternalName"))
                    //.Value(Model.Participants).HtmlAttributes(new { style = "width:300px" })
                    )

        @Html.LabelFor(m => m.Partner)<br />
        @Html.Kendo().TextBoxFor(m => m.Partner)<br />
        @Html.LabelFor(m => m.Description)<br />
        @Html.TextAreaFor(m => m.Description, new { @class = "k-textbox" })<br />
        @Html.LabelFor(m => m.RegistrationRadius)<br />
        @Html.Kendo().DropDownListFor(m => m.RegistrationRadius).BindTo(range).HtmlAttributes(new { style = "width:300px" })<br />
        @Html.LabelFor(m => m.MaxStoresPerVolunteer)<br />
        @Html.Kendo().DropDownListFor(m => m.MaxStoresPerVolunteer).BindTo(maxStores).HtmlAttributes(new { style = "width:300px" })<br />
        @Html.LabelFor(x => x.EventClosed)        
        @Html.CheckBox("EventClosed", Model.EventClosed, new { @id = "EventClosed" })
        @Html.LabelFor(x => x.CollectionBeginsUtc)<br />
        @Html.Kendo().DateTimePickerFor(x => x.CollectionBeginsUtc).Value(Model.PublishToWebUtc).HtmlAttributes(new { style = "width:300px" })<br />
        @Html.LabelFor(x => x.CollectionEndsUtc)<br />
        @Html.Kendo().DateTimePickerFor(x => x.CollectionEndsUtc).Value(Model.UnpublishFromWebUtc).HtmlAttributes(new { style = "width:300px" })<br />
        @Html.LabelFor(x => x.RegistrationOpensUtc)<br />
        @Html.Kendo().DateTimePickerFor(x => x.RegistrationOpensUtc).HtmlAttributes(new { style = "width:300px" })<br />



        @Html.ValidationMessageFor(m => m.RegistrationOpensUtc)<br />
        @Html.LabelFor(x => x.RegistrationClosesUtc)<br />
        @Html.Kendo().DateTimePickerFor(x => x.RegistrationClosesUtc).HtmlAttributes(new { style = "width:300px" })<br />
        @Html.ValidationMessageFor(m => m.RegistrationClosesUtc)<br />
        @Html.LabelFor(x => x.PublishToEventCalendar)<span>&nbsp;&nbsp;&nbsp;&nbsp;</span>
        @Html.CheckBox("PublishToEventCalendar", Model.PublishToEventCalendar ?? false, new { @id = "PublishToEventCalendar", style = "min-width:20px;" })
        @Html.ValidationMessageFor(m => m.PublishToEventCalendar)<br />
        @Html.HiddenFor(x => x.PublishToWebUtc, new { Value = DateTime.UtcNow }) //ITEMS NEEDED CONFIRMATION OF WHY FROM ROY
        @Html.HiddenFor(x => x.UnpublishFromWebUtc, new { Value = DateTime.UtcNow }) //ITEMS NEEDED CONFIRMATION OF WHY FROM ROY
        @Html.HiddenFor(x => x.EventTypeId)
        
        @Html.HiddenFor(x => x.Start, new { Value = DateTime.UtcNow }) //ITEMS NEEDED CONFIRMATION OF WHY FROM ROY
        @Html.HiddenFor(x => x.End, new { Value = DateTime.UtcNow }) //ITEMS NEEDED CONFIRMATION OF WHY FROM ROY
        @Html.HiddenFor(x => x.Id)
        @Html.HiddenFor(x => x.TimeStamp.UtcCreatedDate, new { Value = DateTime.UtcNow }) //ITEMS NEEDED CONFIRMATION OF WHY FROM ROY
        @Html.HiddenFor(x => x.TimeStamp.UtcLastModifiedDate, new { Value = DateTime.UtcNow }) //ITEMS NEEDED CONFIRMATION OF WHY FROM ROY

        <input type="button" value="save event" id="saveButton" />

    }
</div>
<div id="spin" class="k-loading-mask" style="display:none;width:100%;height:100%;position:absolute;top:0px">
    <span class="k-loading-text">Loading...</span>
    <div class="k-loading-image">
        <div class="k-loading-color">
        </div>
    </div>
</div>
<span id="staticNotification"></span>

<div id="locationVolunteerHolderDiv" style="width: 69%; float: left;">
        @*@if (!saveAsNew)
        {
            @Html.Action("GetEventTabs", "CollectionEvent", new { id = Model.Id })
      
        }*@
</div>

<script type="text/javascript">
    $(document).ready(function () {
        @if (!saveAsNew)
            {
                @:loadTabs();
            }
    });

    function loadTabs() {
        var u = "@Url.Action("GetEventTabs", "CollectionEvent", new {id = Model.Id})";
        $("#locationVolunteerHolderDiv").load(u);
    }


        $(document).ready(function () {

            $("#saveButton").click(function () {
                showSpinner();
            });
        });

    var staticNotification = $("#staticNotification").kendoNotification({ appendTo: "#errorMessage" }).data("kendoNotification");

    function showSpinner() {
        $("#spin").show();
        var form = $("#collectionEventForm");
        $.ajax({
            url: "/Events/CollectionEvent/New",
            type: "POST",
            data: $(form).serialize(),
            xhrFields: { withCredentials: true },
            success: function (msg) {
                //alert(msg);
               // updateSuccess();
                $("#spin").hide();
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert("error" + textStatus);
                failure();

                $("#spin").hide();
            }
        });
    }

    function hideSpinner() {
        $("#spin").hide();
    @if (saveAsNew){
            @:$("#myButton").hide();
    }
        $("#myButton").closest("form").prop("disabled", true).find("input,select,textarea").prop("disabled", true);
        $("#MaxStoresPerVolunteer").data("kendoDropDownList").enable(false);
        $("#RegistrationRadius").data("kendoDropDownList").enable(false);
        $("#OwnerId").data("kendoDropDownList").enable(false);
        //$("#Participants").data("kendoMultiSelect").enable(false);
        $("#CollectionBeginsUtc").data("kendoDateTimePicker").enable(false);
        $("#CollectionEndsUtc").data("kendoDateTimePicker").enable(false);
        $("#RegistrationOpensUtc").data("kendoDateTimePicker").enable(false);
        $("#RegistrationClosesUtc").data("kendoDateTimePicker").enable(false);
    }

    function genscript() {
        var dropdownlist1 = $("#Submitter_Caregiver_Gender").data("kendoDropDownList");
        if (dropdownlist1.value() == "") {
            $("#Submitter_Caregiver_Gender").closest(".k-widget").css("border", "1px solid crimson");
        }
    }


    function AddressCheck() {
        var zip = $('.location-zip').val();
        var city = $('.location-city').val();
        var state = $('.location-state').val();
        var changed = false;
        var u = "@Url.Action("VerifyCityStateZip","Staff")?zip="+zip;
        $.ajax({
            type: 'GET',
            async: false,
            dataType: "json",
            url: u,
            traditional: true,
            success: function (data) {

                if (city.toUpperCase() != data.City) {
                    $('.location-city').val(data.City).change();
                    changed = true;
                }
                if (state != data.State) {
                    $('.location-state').val(data.State).change();
                    changed = true;
                }
                //if (changed) {
                //    alert('Your Address information has been updated to match our records. \n' +
                //        'your City, State, and Zip have been updated to City: ' + s[0].City + ', and State: ' + s[0].State + ' for Zip: ' + zip + '.')
                //}
            }

        });
    }

    </script>

Areas/Events/Views/CollectionEvent/_Success.cshtml
<p>Success</p>
<h2>Success</h2>